-- ============================================================================
-- BOOKIE - Database Initialization Script for Oracle XE
-- ============================================================================
-- This script is re-executable: it drops existing tables before creating new ones
-- Compatible with Oracle XE
-- Author: Database Admin
-- Created: May 2026
-- ============================================================================

-- ============================================================================
-- DROP EXISTING TABLES (if they exist) - for re-executability
-- ============================================================================
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE LOANS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BOOKS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USERS';
EXCEPTION
   WHEN OTHERS THEN
      IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- ============================================================================
-- TABLE: USERS
-- Description: Stores user information for the Bookie system
-- Columns:
--   - USER_ID: Auto-generated primary key
--   - NAME: User's full name (max 100 characters)
--   - DOCUMENT_ID: User's document/ID (max 20 characters, unique)
--   - EMAIL: User's email (max 100 characters, unique)
--   - CREATED_AT: Timestamp of user creation (defaults to SYSDATE)
-- ============================================================================
CREATE TABLE USERS (
    USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(100) NOT NULL,
    DOCUMENT_ID VARCHAR2(20) UNIQUE NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE
);

-- ============================================================================
-- TABLE: BOOKS
-- Description: Stores book inventory information
-- Columns:
--   - BOOK_ID: Auto-generated primary key
--   - TITLE: Book title (max 200 characters)
--   - AUTHOR: Book author name (max 150 characters)
--   - AVAILABILITY: Number of copies available (default: 10)
--   - CREATED_AT: Timestamp of book creation (defaults to SYSDATE)
-- ============================================================================
CREATE TABLE BOOKS (
    BOOK_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    AUTHOR VARCHAR2(150) NOT NULL,
    AVAILABILITY NUMBER DEFAULT 10 NOT NULL,
    CREATED_AT DATE DEFAULT SYSDATE
);

-- ============================================================================
-- TABLE: LOANS
-- Description: Stores loan information with referential integrity
-- Columns:
--   - LOAN_ID: Auto-generated primary key
--   - USER_ID: Foreign key referencing USERS (ON DELETE CASCADE)
--   - BOOK_ID: Foreign key referencing BOOKS
--   - LOAN_DATE: Date when the book was loaned (defaults to SYSDATE)
--   - RETURN_DATE: Date when the book was returned (nullable)
--   - STATUS: Loan status (default: 'BORROWED')
-- Foreign Key Constraints:
--   - FK_LOAN_USER: User deletion cascades to delete associated loans
--   - FK_LOAN_BOOK: Book reference constraint
-- ============================================================================
CREATE TABLE LOANS (
    LOAN_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    BOOK_ID NUMBER NOT NULL,
    LOAN_DATE DATE DEFAULT SYSDATE,
    RETURN_DATE DATE,
    STATUS VARCHAR2(50) DEFAULT 'BORROWED',
    CONSTRAINT FK_LOAN_USER FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_LOAN_BOOK FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID)
);

-- ============================================================================
-- INSERT TEST DATA: USERS (3 users)
-- ============================================================================
INSERT INTO USERS (NAME, DOCUMENT_ID, EMAIL) VALUES ('Juan Pérez', '12345678-9', 'juan.perez@example.com');
INSERT INTO USERS (NAME, DOCUMENT_ID, EMAIL) VALUES ('María García', '98765432-1', 'maria.garcia@example.com');
INSERT INTO USERS (NAME, DOCUMENT_ID, EMAIL) VALUES ('Carlos López', '55555555-5', 'carlos.lopez@example.com');

-- ============================================================================
-- INSERT TEST DATA: BOOKS (5 books with initial AVAILABILITY = 10)
-- ============================================================================
INSERT INTO BOOKS (TITLE, AUTHOR, AVAILABILITY) VALUES ('100 Años de Soledad', 'Gabriel García Márquez', 10);
INSERT INTO BOOKS (TITLE, AUTHOR, AVAILABILITY) VALUES ('Don Quijote', 'Miguel de Cervantes', 10);
INSERT INTO BOOKS (TITLE, AUTHOR, AVAILABILITY) VALUES ('El Código Da Vinci', 'Dan Brown', 10);
INSERT INTO BOOKS (TITLE, AUTHOR, AVAILABILITY) VALUES ('1984', 'George Orwell', 10);
INSERT INTO BOOKS (TITLE, AUTHOR, AVAILABILITY) VALUES ('Orgullo y Prejuicio', 'Jane Austen', 10);

-- ============================================================================
-- INSERT TEST DATA: LOANS (sample loan records)
-- ============================================================================
INSERT INTO LOANS (USER_ID, BOOK_ID, STATUS) VALUES (1, 1, 'BORROWED');
INSERT INTO LOANS (USER_ID, BOOK_ID, STATUS) VALUES (1, 2, 'RETURNED');
INSERT INTO LOANS (USER_ID, BOOK_ID, STATUS) VALUES (2, 3, 'BORROWED');
INSERT INTO LOANS (USER_ID, BOOK_ID, STATUS) VALUES (3, 4, 'BORROWED');

-- ============================================================================
-- CREATE INDICES FOR PERFORMANCE OPTIMIZATION
-- ============================================================================
CREATE INDEX IDX_LOANS_USER_ID ON LOANS(USER_ID);
CREATE INDEX IDX_LOANS_BOOK_ID ON LOANS(BOOK_ID);
CREATE INDEX IDX_LOANS_STATUS ON LOANS(STATUS);
CREATE INDEX IDX_BOOKS_TITLE ON BOOKS(TITLE);

-- ============================================================================
-- COMMIT ALL CHANGES
-- ============================================================================
COMMIT;

-- ============================================================================
-- VERIFICATION QUERIES (Optional - execute these to verify setup)
-- ============================================================================
-- Uncomment the following queries to verify the tables were created correctly:
-- 
-- SELECT 'USERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM USERS
-- UNION ALL
-- SELECT 'BOOKS', COUNT(*) FROM BOOKS
-- UNION ALL
-- SELECT 'LOANS', COUNT(*) FROM LOANS;
--
-- SELECT * FROM USERS;
-- SELECT * FROM BOOKS;
-- SELECT * FROM LOANS;
-- ============================================================================
