spring.application.name=bff

# Configuración LOCAL - Para desarrollo con emulator o localhost
# Configuración de Azure Functions (FaaS) - REST (Usuarios)
faas.user.url=http://localhost:7071/api/users

# Configuración de Azure Functions (FaaS) - GraphQL (Préstamos)
faas.graphql.query.url=http://localhost:7071/api/graphql/loans/query
faas.graphql.mutation.url=http://localhost:7071/api/graphql/loans/mutation

# Configuración de Datasource (Oracle)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=bookie_admin
spring.datasource.password=Admin1.
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

# Configuración de logging
logging.level.root=INFO
logging.level.duoc.bff=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Configuración de Jackson para omitir campos null en la serialización JSON
spring.jackson.default-property-inclusion=non_null
