spring.application.name=bff

# Configuración de Azure Functions (FaaS)
faas.user.url=https://bookie-functions.azurewebsites.net/api/users
faas.loan.url=https://bookie-functions.azurewebsites.net/api/loans

# Configuración de logging
logging.level.root=INFO
logging.level.duoc.bff=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Configuración de Jackson para omitir campos null en la serialización JSON
spring.jackson.default-property-inclusion=non_null
