spring.application.name=bff

# Configuración de Azure Functions (FaaS) - REST (Usuarios se mantiene igual)
faas.user.url=https://bookie-functions.azurewebsites.net/api/users

# Configuración de Azure Functions (FaaS) - GraphQL (Nuevas rutas para Préstamos)
faas.graphql.query.url=https://bookie-functions.azurewebsites.net/api/graphql/loans/query
faas.graphql.mutation.url=https://bookie-functions.azurewebsites.net/api/graphql/loans/mutation
# Configuración de logging
logging.level.root=INFO
logging.level.duoc.bff=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.http=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Configuración de Jackson para omitir campos null en la serialización JSON
spring.jackson.default-property-inclusion=non_null
